application: comunicacion-falabella
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /css
  static_dir: css

- url: /js
  static_dir: js

- url: /images
  static_dir: images

- url: /.*
  script: comunicacion.app

libraries:
- name: jinja2
  version: latest

builtins:
- remote_api: on

